# Generated by Django 3.1.1 on 2021-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='username',
            field=models.CharField(default='patient', max_length=50),
        ),
    ]
