# Generated by Django 3.1.dev20191223111756 on 2021-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='label',
            field=models.CharField(default='Patient', max_length=200),
        ),
    ]
