# Generated by Django 3.1.1 on 2021-02-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patientprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='label',
        ),
    ]
