# Generated by Django 3.1.1 on 2021-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patientprofile_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='label',
            field=models.CharField(default='patients', max_length=200),
        ),
    ]
