# Generated by Django 3.1.dev20191223111756 on 2021-02-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210213_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf',
            field=models.FileField(upload_to='prescription_pdfs'),
        ),
    ]
