# Generated by Django 3.1.dev20191223111756 on 2021-02-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20210213_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HealthConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentsandMedicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='addressline1',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='addressline2',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='zipcode',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='Records',
        ),
        migrations.AddField(
            model_name='treatmentsandmedicines',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientProfile'),
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientProfile'),
        ),
        migrations.AddField(
            model_name='healthconditions',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientProfile'),
        ),
        migrations.AddField(
            model_name='allergies',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientProfile'),
        ),
    ]
