# Generated by Django 3.1.6 on 2021-02-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20210214_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='number',
            field=models.CharField(default='012345 67898', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='pronouns',
            field=models.CharField(default='they/them', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='race',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sex',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
