# Generated by Django 3.1.6 on 2021-02-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patientprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyle',
            name='drinker',
            field=models.CharField(default='social', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='smoker',
            field=models.CharField(default='heavy', max_length=200),
            preserve_default=False,
        ),
    ]
