# Generated by Django 3.1.6 on 2021-02-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20210213_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifestyle',
            name='drinker',
        ),
        migrations.RemoveField(
            model_name='lifestyle',
            name='smoker',
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='amount',
            field=models.CharField(default='heavy', max_length=200),
            preserve_default=False,
        ),
    ]
