# Generated by Django 3.1.6 on 2021-02-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20210213_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='zipcode',
            field=models.CharField(max_length=12),
        ),
    ]
