# Generated by Django 3.1.6 on 2021-02-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20210213_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='label',
        ),
    ]
