# Generated by Django 3.1.6 on 2021-02-14 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_license_number', models.CharField(default=' ', max_length=50)),
                ('proof', models.FileField(null=True, upload_to='proof_pdfs')),
                ('label', models.CharField(default='Doctor', max_length=200)),
                ('country', models.CharField(default='India', max_length=200)),
                ('city', models.CharField(default='Delhi', max_length=200)),
                ('date_of_birth', models.DateField(default='2000-02-03')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
