# Generated by Django 3.1.dev20191223111756 on 2021-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(default='Delhi', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='country',
            field=models.CharField(default='India', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(default='2000-02-03'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_license_number',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
