# Generated by Django 3.1.dev20191223111756 on 2021-02-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20210213_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='proof',
            field=models.FileField(null=True, upload_to='proof_pdfs'),
        ),
    ]
